In [36]:
import sqlite3 
import pandas as pd
import matplotlib.pyplot as plt

Commande pour lire le fichier CSV téléchargé :

sqlite3 COVID.db 
sqlite> .mode csv covid_data 
sqlite> .import owid-covid-data.csv covid_data
sqlite> .read covid_data.sql

In [2]:
conn = sqlite3.connect("COVID.db")

In [3]:
cursor = conn.cursor()

In [4]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('covid_data',)]

In [5]:
df = pd.read_sql_query("SELECT * FROM covid_data", conn)
df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,2020-02-24,1.0,1.0,,,,,...,1803.987,,597.029,9.59,,,37.746,0.5,64.83,0.511
1,AFG,Asia,Afghanistan,2020-02-25,1.0,0.0,,,,,...,1803.987,,597.029,9.59,,,37.746,0.5,64.83,0.511
2,AFG,Asia,Afghanistan,2020-02-26,1.0,0.0,,,,,...,1803.987,,597.029,9.59,,,37.746,0.5,64.83,0.511
3,AFG,Asia,Afghanistan,2020-02-27,1.0,0.0,,,,,...,1803.987,,597.029,9.59,,,37.746,0.5,64.83,0.511
4,AFG,Asia,Afghanistan,2020-02-28,1.0,0.0,,,,,...,1803.987,,597.029,9.59,,,37.746,0.5,64.83,0.511
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86413,ZWE,Africa,Zimbabwe,2021-05-02,38281.0,21.0,27.857,1570.0,2.0,1.857,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571
86414,ZWE,Africa,Zimbabwe,2021-05-03,38293.0,12.0,27.286,1573.0,3.0,1.857,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571
86415,ZWE,Africa,Zimbabwe,2021-05-04,38327.0,34.0,23.286,1574.0,1.0,1.286,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571
86416,ZWE,Africa,Zimbabwe,2021-05-05,38357.0,30.0,23.714,1574.0,0.0,1.286,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571
86417,ZWE,Africa,Zimbabwe,2021-05-06,38398.0,41.0,23.286,1575.0,1.0,1.143,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571

Requête pour afficher toutes les colonnes

In [6]:
columns = pd.read_sql_query ("SELECT name FROM PRAGMA_TABLE_INFO('covid_data')", conn)
columns

                                     name
0                                iso_code
1                               continent
2                                location
3                                    date
4                             total_cases
5                               new_cases
6                      new_cases_smoothed
7                            total_deaths
8                              new_deaths
9                     new_deaths_smoothed
10                total_cases_per_million
11                  new_cases_per_million
12         new_cases_smoothed_per_million
13               total_deaths_per_million
14                 new_deaths_per_million
15        new_deaths_smoothed_per_million
16                      reproduction_rate
17                           icu_patients
18               icu_patients_per_million
19                          hosp_patients
20              hosp_patients_per_million
21                  weekly_icu_admissions
22      weekly_icu_admissions_per_million
23                 weekly_hosp_admissions
24     weekly_hosp_admissions_per_million
25                              new_tests
26                            total_tests
27               total_tests_per_thousand
28                 new_tests_per_thousand
29                     new_tests_smoothed
30        new_tests_smoothed_per_thousand
31                          positive_rate
32                         tests_per_case
33                            tests_units
34                     total_vaccinations
35                      people_vaccinated
36                people_fully_vaccinated
37                       new_vaccinations
38              new_vaccinations_smoothed
39         total_vaccinations_per_hundred
40          people_vaccinated_per_hundred
41    people_fully_vaccinated_per_hundred
42  new_vaccinations_smoothed_per_million
43                       stringency_index
44                             population
45                     population_density
46                             median_age
47                          aged_65_older
48                          aged_70_older
49                         gdp_per_capita
50                        extreme_poverty
51                  cardiovasc_death_rate
52                    diabetes_prevalence
53                         female_smokers
54                           male_smokers
55                 handwashing_facilities
56             hospital_beds_per_thousand
57                        life_expectancy
58                human_development_index

1. How many countries are included in our data set?

In [7]:
location = pd.read_sql_query("SELECT COUNT (DISTINCT location) FROM covid_data", conn)
location

   COUNT (DISTINCT location)
0                        219

2. When was the most recent entry?

In [8]:
date = pd.read_sql_query("SELECT date FROM covid_data ORDER BY date DESC LIMIT 1", conn)
date

         date
0  2021-05-06

3. What country had the highest single day deaths per million?

In [47]:
country_highest = pd.read_sql_query("SELECT location FROM covid_data WHERE new_deaths_per_million ORDER BY new_deaths_per_million ASC LIMIT 1", conn)
country_highest

  location
0    India

4. Select any country. How many times have the deaths per million exceeded 1,000 in one day?

In [50]:
#rand = pd.read_sql_query("SELECT location FROM covid_data GROUP BY RANDOM() LIMIT 1", conn)
#rand

  location
0  Nigeria

In [23]:
rand_1 = pd.read_sql_query("SELECT location, COUNT(*) FROM covid_data WHERE new_deaths_per_million > 1000 AND location = 'Poland'", conn)
rand_1

  location  COUNT(*)
0   Poland       171

5. Extract the deaths per million for US, France, and India. Plot the time series data and compare results to what the media is currently saying

In [12]:
france = pd.read_sql_query("SELECT date, new_deaths_per_million FROM covid_data WHERE location = 'France'", conn)
france

           date new_deaths_per_million
0    2020-01-24
1    2020-01-25
2    2020-01-26
3    2020-01-27
4    2020-01-28
..          ...                    ...
464  2021-05-02                  1.658
465  2021-05-03                  4.564
466  2021-05-04                  3.771
467  2021-05-05                   3.58
468  2021-05-06                  3.214

[469 rows x 2 columns]

In [13]:
india = pd.read_sql_query("SELECT date, new_deaths_per_million FROM covid_data WHERE location = 'India'", conn)
india

           date new_deaths_per_million
0    2020-01-30
1    2020-01-31
2    2020-02-01
3    2020-02-02
4    2020-02-03
..          ...                    ...
458  2021-05-02                  2.476
459  2021-05-03                  2.499
460  2021-05-04                  2.739
461  2021-05-05                  2.884
462  2021-05-06                    0.0

[463 rows x 2 columns]

In [31]:
us = pd.read_sql_query("SELECT date, new_deaths_per_million FROM covid_data WHERE location = 'United States'", conn)
us

           date new_deaths_per_million
0    2020-01-22
1    2020-01-23
2    2020-01-24
3    2020-01-25
4    2020-01-26
..          ...                    ...
466  2021-05-02                  0.976
467  2021-05-03                  1.459
468  2021-05-04                  2.819
469  2021-05-05                  2.344
470  2021-05-06                  2.375

[471 rows x 2 columns]

6. Plot the deaths per million and cases per million by continent for your birthday in 2020. What does the data say?

In [55]:
continent = pd.read_sql_query("SELECT continent, COUNT (*) total_deaths_per_million FROM covid_data WHERE date = '2020-01-01' GROUP BY continent", conn)
continent

       continent  total_deaths_per_million
0  North America                         1
1  South America                         1

In [56]:
continent_1 = pd.read_sql_query("SELECT continent, COUNT (*) total_cases_per_million FROM covid_data WHERE date = '2020-01-01' GROUP BY continent", conn)
continent_1

       continent  total_cases_per_million
0  North America                        1
1  South America                        1

7. Plot the lockdown stringency for each country and color the scatter points by continent. Any insights?